# Generated by Django 4.0.6 on 2022-07-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Пользователь'), ('moderator', 'Mодератор'), ('admin', 'Aдмин')], default='member', max_length=50),
        ),
    ]
